# Generated by Django 6.0.2 on 2026-03-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='sliders/')),
                ('subtitle', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
    ]
