# Generated by Django 6.0.2 on 2026-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_slidermodel_alter_bannermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermodel',
            options={},
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='banner_type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('INTRO', 'Intro')], default='CATEGORY', max_length=20),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
