# Generated by Django 6.0.2 on 2026-03-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_bannermodel_options_bannermodel_banner_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='text_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='text_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='text_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='subtitle_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='subtitle_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='subtitle_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='title_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='title_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
