# Generated by Django 6.0.2 on 2026-03-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogauthormodel_blogcategorymodel_blogmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthormodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='professions',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
